version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    container_name: spring-postgres
    environment:
      - 'POSTGRES_DB=db0'
      - 'POSTGRES_PASSWORD=pass'
      - 'POSTGRES_USER=user'
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d db0"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: